Prevent websocket upgrade from replying with `content-length: 0`
quarkusio/quarkus-http pull request #139
Opened 2023-11-13 16:31 UTC by chonton

Fixes [quarkusio/quarkus #370505](https://github.com/quarkusio/quarkus/issues/37050)

Additionally, using the native vertx implementation increases the number of websocket clients and versions supported.

2023-11-13 18:55 UTC, cescoffier requested changes

2023-11-13 18:55 UTC, cescoffier commented on websocket/vertx/src/main/java/io/undertow/websockets/vertx/VertxWebSocketHttpExchange.java
> +        request.toWebSocket().onSuccess( ws -> {
Avoid lambda please.

2023-11-13 18:56 UTC, cescoffier commented
Would be great to have a test case.

2023-11-13 20:19 UTC, chonton commented
test case is in quarkus integration tests. please note that there currently aren't any tests for the vertx code

2023-11-13 20:35 UTC, chonton commented on websocket/vertx/src/main/java/io/undertow/websockets/vertx/VertxWebSocketHttpExchange.java
> +        request.toWebSocket().onSuccess( ws -> {
done

2023-11-14 06:00 UTC, cescoffier commented
Ah yes... I forgot that this project still use junit 4.

2023-11-14 06:00 UTC, cescoffier approved these changes

2023-11-14 06:02 UTC, stuartwdouglas approved these changes

2023-11-14 06:08 UTC, merged

2024-03-05 16:26 UTC, cescoffier commented
@chonton I will revert this PR, unfortunately.  
It is breaking sub-protocols (see https://github.com/quarkusio/quarkus/issues/39082). I'm not totally sure why. Let's revert and investigate.

2025-01-09 08:48 UTC, michaelfrid commented
@chonton @cescoffier 
Hello. We just encounter this issue in Quarkus 3,2,X and 3.15.X. It causes our .Net clients to close websocket connection after some period of time. Are there any plans to fix it ?
Thanks a lot

2025-01-09 10:13 UTC, cescoffier commented
Did you try with WebSocket Next?

2025-01-09 10:14 UTC, cescoffier commented
(We reverted the fix as it introduced a regression)

2025-01-09 10:30 UTC, michaelfrid commented
I see it's marked as experimental feature. Is it stable enough to be used in the production environment ?
It also means we need to rewrite our current implementation, right ?

2025-01-09 10:49 UTC, cescoffier commented
Yes, it is not quite mature. It is going to become our recommended approach
for WebSockets.

Le jeu. 9 janv. 2025 à 11:31, michaelfrid ***@***.***> a
écrit :

> @cescoffier <https://github.com/cescoffier>
> I see it's marked as experimental feature. Is it stable enough to be used
> in the production environment ?
> It also means we need to rewrite our current implementation, right ?
> Thank you
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus-http/pull/139#issuecomment-2579752388>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADCG7NGNVXFER53I3MJIOT2JZFYDAVCNFSM6AAAAABU3ULHWCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNZZG42TEMZYHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-01-09 12:45 UTC, michaelfrid commented
@cescoffier
So what should we do for meanwhile ? Any chances the original issue will be fixed ?

2025-01-09 15:04 UTC, cescoffier commented
Sorry, it is quite mature :-) 
I would recommend switching.

I don't believe this issue will be fixed anytime soon. At least I do not have the bandwidth.